/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QJB42J1Bnbd
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import Image from "next/image";
import makers from "/makers.webp";

export function HomePage() {
  return (
    <main className="flex flex-col gap-12 md:gap-20">
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
        <div className="mx-auto container px-4 md:px-6 flex items-start justify-between">
          <div className="space-y-6">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
              making@umn
            </h1>
            <p className="max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              We host weekly sessions for you to work on your passion projects
              with likeminded people.
            </p>
            <div className="space-x-4">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-lg font-medium shadow-md transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 disabled:pointer-events-none disabled:opacity-50"
                href="https://lu.ma/making-umn"
              >
                Attend a Session
              </Link>
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-lg font-medium shadow-md transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 disabled:pointer-events-none disabled:opacity-50"
                href="https://www.figma.com/file/5v5Y8XMrT9Ib0rvYgx7pSK/making@umn-scrapbook?type=whiteboard&node-id=8-11&t=9dtEc3yHBrG1tKz8-0"
              >
                Our Projects
              </Link>
            </div>
          </div>
          <Image
            alt="Image"
            className="mx-auto rounded-xl object-cover object-center sm:w-full lg:order-last shadow-xl"
            height="400"
            src={makers}
            width="500"
          />
        </div>
      </section>
    </main>
  );
}
