/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QJB42J1Bnbd
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import Image from "next/image";
import makers from "/makers.webp";
import { Button } from "./ui/button";
import { BackgroundGradientAnimationDemo } from "./blob";
export function HomePage() {
  return (
    <main className="flex flex-col gap-12 md:gap-20">
      <BackgroundGradientAnimationDemo>
        <section className="absolute left-1/2 top-1/2 z-10 w-full -translate-x-1/2 -translate-y-1/2">
          <div className="container mx-auto flex h-full flex-wrap items-center justify-between px-4 sm:flex-nowrap md:px-6">
            <div className="md:max-w-1/2 lg:max-w-1/2 space-y-6">
              <h1 className="text-5xl font-bold tracking-tighter text-white opacity-90">
                making@umn
              </h1>
              <p className="max-w-[700px] text-base/relaxed text-gray-300 md:text-xl/relaxed">
                We host weekly sessions for you to work on your passion projects
                with likeminded people.
              </p>
              <div className="space-x-2 pb-4 md:space-x-4">
                <Link href="https://lu.ma/making-umn">
                  <Button variant="outline" className="opacity-90 shadow-md">
                    Attend a Session
                  </Button>
                </Link>
                <Link href="https://www.figma.com/file/5v5Y8XMrT9Ib0rvYgx7pSK/making@umn-scrapbook?type=whiteboard&node-id=8-11&t=9dtEc3yHBrG1tKz8-0">
                  <Button
                    variant="ghost"
                    className="border text-white shadow-md"
                  >
                    Our Projects
                  </Button>
                </Link>
              </div>
            </div>
            <Image
              alt="Image"
              className="opacity-88 mx-auto rounded-xl shadow-xl md:w-1/2"
              src={makers}
            />
          </div>
        </section>
      </BackgroundGradientAnimationDemo>
    </main>
  );
}
